### ISSUE TITLE
紳士動態牆：應該要將同一位成員所傳的連續訊息，視為是「一則」留言。並且應該要限定同一個貼文三小時內不能推播到第兩次

### ISSUE THREAD

**Issue by Johnny850807** [Waterball-Software-Academy/WSA-Utopia-Discord-Bot#58]
應該要將同一位成員所傳的連續訊息，視為是「一則」留言。
![image](https://user-images.githubusercontent.com/23109467/231169912-6b135633-885b-4df8-810f-750d8e782d77.png)

現況：
紳士動態牆功能，只要同一貼文下出現 4 則以上的留言，就會做一次留言的摘要。
如果有人高頻率連續回應，則會導致動態牆對同一個人的留言不斷做摘要。

**Comment by aa89227** [comment]
我覺得這很有必要，每個人習慣不同，但比較糟糕的情況會是，有人連續傳訊息後，中間會插一則別人的訊息。
